### ISSUE TITLE
Saved datafile names

### ISSUE THREAD

**Issue by Eflores89** [alanjordan101/USPresDebates#2]
I'm taking a look at some data files. They are named consistently outside of R, example : 
`D2016RUndercardNorthCharlestonSC.Rdata`

But, how are you saving them? Using `save()`? 

Because it seems you are saving the object, named `deb` as `D2016RUndercardNorthCharlestonSC.Rdata`. 

Thus, this is problematic because R will read in as an object named the same as how you saved it. 

When I `load()` I get an object named `deb`.

FYI, I'm going to rename all objects and save again. But because we are working together, please keep a careful track of the objects your changing, so that I can resave them inside the package. 

Does this make sense?

**Comment by Eflores89** [comment]
Or should I only build the package with some debates and files we know are already correct? And add as we progress?

**Comment by alanjordan101** [comment]
1) You're ahead of me. None of these files are ready yet. This is still in the debug stage. I am trying to clean up records where the PERSON field is garbage or a piece of the MESSAGE field. 

Next I will go through the message fields and separate pieces that should mark a new PERSON and remove topic heading that are still in some of the transcripts. There over 140 files so it's time consuming.

For cleaning, I'm grouping them by election so that it's manageable. There is a clustering of PERSON values by election. I'm building tables to link PERSON to some other variables that are stable within an election, but not between elections. When it's all done, we can put them together in one big file or election files or both.

2) You should get a file named deb. I'm saving them with the save command

save(deb, file=paste0('D',debate,".Rdata"))

where debate is pulled off the dl3.csv file. It might be better use assign() and give them matching names. I may change that later. You could write a more elegant piece of code for step 3 program.
